# Specify the provider and build configuration
[phases.setup]
nixPkgs = [
    # Core dependencies
    "nodejs_20",
    "bun",
    "ffmpeg",
    "opus",
    "nodePackages.node-gyp",
    "python3",
    "pkg-config",
    "gcc",
    "make",

    # Audio processing dependencies
    "libopus",
    "libogg",
    "libsodium",

    # System dependencies
    "autoconf",
    "automake",
    "libtool",

    # Build essentials
    "gnumake",
    "nodejs.gyp",
    "python3Full",
]

[phases.install]
cmds = [
    "npm config set python python3",
    "npm install -g node-gyp",
    "npm install -g node-pre-gyp",
]

[phases.build]
cmds = [
    "npm config set python python3",
    "export NODE_GYP_FORCE_PYTHON=python3",
    "npm rebuild",
    "bun install --no-save",
]

[start]
cmd = "bun start"

[variables]
NODE_ENV = "production"
PYTHON = "python3"
NODE_GYP_FORCE_PYTHON = "python3"
PATH = "/usr/local/bin:/usr/bin:/bin:/app/node_modules/.bin"
