[phases.setup]
nixPkgs = [
    "nodejs_18",
    "ffmpeg",
    "libogg",
    "libopus",
    "libsodium",
    "libtool",
    "autoconf",
    "automake",
    "python3Full",
    "git",
    "gcc",
    "opusTools",
    "opusfile",
    "gnumake",
    "coreutils",
    "binutils",
    "bash",
    "corepack",
]

[phases.install]
cmds = [
    'npm install -g corepack',
    "corepack enable",
    "corepack prepare pnpm@9.9.0 --activate",
    "npm install -g node-gyp",
    "pnpm install",
]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
