# Specify the provider and build configuration
[phases.setup]
nixPkgs = [
    "nodejs_18",
    "bun",
    "ffmpeg",
    "libogg",
    "libopus",
    "libsodium",
    "libtool",
    "autoconf",
    "automake",
    "python3Full",
    "git",
    "gcc",
    "opusTools",
    "opusfile",
]

[phases.install]
# Add node-gyp to PATH and run installations
cmds = [
    "export PATH=/root/.bun/bin:$PATH",
    "bun install -g node-gyp",
    "bun install",
]

[start]
cmd = "bun start"

[variables]
NODE_ENV = "production"
PATH = "/root/.bun/bin:$PATH"
