# Specify the provider and build configuration
[phases.setup]
nixPkgs = [
    "nodejs_18",
    "bun",
    "ffmpeg",
    "libogg",
    "libopus",
    "libsodium",
    "libtool",
    "autoconf",
    "automake",
    "python3Full",
    "git",
    "gcc",
    "opusTools",
    "opusfile",
]

[phases.install]
cmds = ["bun install"]

[start]
cmd = "bun start"

[variables]
NODE_ENV = "production"
