# Specify the provider and build configuration
[phases.setup]
nixPkgs = [
    "nodejs_20",
    "bun",
    "ffmpeg",
    "opus",
    "nodePackages.node-gyp",
    "python3",
    "pkg-config",
    "gcc",
    "gnumake",
    "libogg",
    "libopus",
    "libsodium",
    "libtool",
    "autoconf",
    "automake",
    "python3Full",
    "npm",
    "git",
]

[phases.install]
cmds = [
    "npm config set python python3",
    "npm install -g node-gyp",
    "npm install",
]

[phases.setup.env]
PYTHON = "python3"
NODE_GYP_FORCE_PYTHON = "python3"
PATH = "/usr/local/bin:/usr/bin:/bin:/app/node_modules/.bin"

[phases.build]
cmds = ["npm rebuild"]

[start]
cmd = "bun start"

[variables]
NODE_ENV = "production"
