[phases.setup]
nixPkgs = [
    "nodejs_20",
    "bun",
    "ffmpeg",
    "libogg",
    "libopus",
    "libsodium",
    "libtool",
    "autoconf",
    "automake",
    "python3Full",
    "git",
    "gcc",
    "opusTools",
    "opusfile",
    "gnumake",
    "coreutils",
    "binutils",
    "bash",        # Added this line
]

[phases.install]
# Add node-gyp to PATH and run installations with proper environment
cmds = [
    "export PATH=/root/.bun/bin:/root/.nix-profile/bin:$PATH",
    "export CPATH=/root/.nix-profile/include",
    "export LIBRARY_PATH=/root/.nix-profile/lib",
    "bun install -g node-gyp",
    "bun install",
]

[start]
cmd = "bun start"

[variables]
NODE_ENV = "production"
PATH = "/root/.bun/bin:/root/.nix-profile/bin:$PATH"
CPATH = "/root/.nix-profile/include"
LIBRARY_PATH = "/root/.nix-profile/lib"
