# Specify the provider and build configuration
[phases.setup]
nixPkgs = [
    # Core dependencies
    "nodejs_20",
    "bun",
    "ffmpeg",
    "opus",
    "nodePackages.node-gyp",
    "python3",
    "pkg-config",
    "gcc",
    "make",

    # Audio processing dependencies
    "libopus",
    "libogg",
    "libsodium",

    # System dependencies
    "autoconf",
    "automake",
    "libtool",
    "gnumake",
    "python3Full",

    # Additional build tools
    "npm",
    "git",
]

[phases.install]
cmds = [
    "npm config set python python3",
    "npm install -g node-gyp",
    "npm install -g node-pre-gyp",
    "npm install",                   # Use npm for initial install
]

[phases.setup.env]
PYTHON = "python3"
NODE_GYP_FORCE_PYTHON = "python3"
PATH = "/usr/local/bin:/usr/bin:/bin:/app/node_modules/.bin"

[phases.build]
cmds = [
    "npm rebuild",
    "bun install --no-save", # Try bun install after npm install
]

[start]
cmd = "bun start"

[variables]
NODE_ENV = "production"
