# Specify the provider and build configuration
[phases.setup]
nixPkgs = [
    "nodejs_18",
    "bun",
    "ffmpeg",
    "libogg",
    "libopus",
    "libsodium",
    "libtool",
    "autoconf",
    "automake",
    "python3Full",
    "git",
    "gcc",
    "pkg-config",
    "gnumake",
]

[phases.install]
cmds = [
    "bun install",
    "npm install -g node-gyp",
    "npm install --build-from-source --legacy-peer-deps",
]

[start]
cmd = "bun start"

[variables]
NODE_ENV = "production"
